# Generated by Django 5.1.2 on 2024-10-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultarDatos',
        ),
        migrations.DeleteModel(
            name='PruebaMensaje',
        ),
        migrations.DeleteModel(
            name='ReportePDF',
        ),
        migrations.DeleteModel(
            name='ResumenClasificacionFecha',
        ),
        migrations.DeleteModel(
            name='ResumenRangoFechas',
        ),
    ]
